### ISSUE TITLE
db.Select(&[]Model) and Join interaction

### ISSUE THREAD

**Issue by Kay-Zee** [go-pg/pg#346] opened 2016-09-28 07:07 UTC
Currently, I have a the following working queries

`db.Model(&[]AStruct{}).ColumnExpr("true AS extra").Where("status = ?", status).Select(&[]AStructWithExtraField)`

and

`db.Model(&[]AStruct{}).Column("JoinTable").ColumnExpr("true AS extra").Where("status = ?", status).Select()`

Both of which work as expected. The first one will select the `extra` property into the array passed into the `Select` function. The second will generate and call the JoinTable correctly and populate the `JoinTable` array in `AStruct`, but since `AStruct` does not have the `extra` properly, that properly is lost.

However, if I combine the two,

`db.Model(&[]AStruct{}).Column("JoinTable").ColumnExpr("true AS extra").Where("status = ?", status).Select(&[]AStructWithExtraField)`

I get an SQL error, of the form `ERROR #42601 syntax error at or near ")"`, from the debug, i can see it's caused by an empty sub query:

`SELECT "joinTable".* FROM "joinTables" AS "joinTable" WHERE (("joinTable"."a_struct_id") IN ())`

I've tried using the `AStructWithExtraField` array in the Models function, i.e. `db.Model(&[]AStructWithExtraField{}).Column("JoinTable").ColumnExpr("true AS extra").Where("status = ?", status).Select()` but that did not work either.

It seems that this style of use works perfect with normal structs, but its when I started using it with slices of structs that I started running into problems.

Any Ideas?

**Comment by vmihailenco** [comment] 2016-09-28 08:20
The problem is that join looks for data in `&[]AStruct`, but data is actually loaded into `&[]AStructWithExtraField`. And I think changing this behavior will complicate internals too much. Probably the right fix is to make queries like

```
db.Model(&[]AStructWithExtraField).Column("JoinTable").ColumnExpr("true AS extra").Where("status = ?", status).Select()
```

do the right thing. Did you try something like
```
type AStructWithExtraField struct {
  TableName `sql:"a_structs"`

  AStruct
  ExtraField string
}
```

?

**Comment by Kay-Zee** [comment] 2016-09-28 16:45
When I try that, I get the error `ERROR #42703 column "JoinTable" does not exist`

I've tried both with and without the `[]*JoinTable` field in the struct with the extra field, but for some reason when i do this the ORM stops perfoming the Join and just assumes its a column name

**Comment by vmihailenco** [comment] 2016-09-29 07:53
I've added experimental support for this in v5:

```
// BookWithCommentCount is like Book model, but has additional CommentCount
// field that is used to select data into it. The use of `pg:",override"` tag
// is essential here and it overrides internal model properties such as table name.
type BookWithCommentCount struct {
	Book `pg:",override"`

	CommentCount int
}
```

I am happy with everything except the tag name, which is a bit confusing. Probably you have some ideas :)

**Comment by vmihailenco** [comment] 2016-10-11 11:37
@Kay-Zee did it work for you?

**Comment by Kay-Zee** [comment] 2016-10-11 20:24
Hey, thanks for following up, I've been using two separate queries in a transaction instead. 

I've been using v4, is v5 stable? If so I may try to find sometime to try it out.

**Comment by jeromenerf** [comment] 2016-10-12 16:51
@vmihailenco I have been experimenting this override tag to implement "User" and "UserWithPassword" (So that the password field won't be accessible from the User model, when JSON serialized, etc).

However, then 

```
	users := []User{}
	_, err = app.DB.Query(
		&users,
		`select
				users.*
			from users, parcels
			where
				st_dwithin(users.geom, parcels.geom, 0.005)`,
	)
```

returns err : `pg: can't find column password in model User`.

If using this pattern, pg should ignore extraneous columns in returns.

NB: I need `Query()` since I need some fancy PostGIS functions and joins that won't play nice with the ORM way.

**Comment by jeromenerf** [comment] 2016-10-14 10:16
@vmihailenco My previous comment may not be as explicit as I thought it was ...

Given:

```
type User struct {
  Name string
  Email string
}

type UserP struct {
  User `pg:",override"`
  Password string
}
```

I can insert some UserP{} but I can't get `Query()` with a `[]User` target to deal with the extra `password` column in the `user` table. 

As a side note, I don't know how to mimic this kind of "multiple from" queries with the orm DSL, a common pattern with geo queries.

**Comment by vmihailenco** [comment] 2016-10-14 12:56
Sorry, was a bit busy with other things.

go-pg returns an error when it can't find a column for data. I think this is generally useful so you don't have to worry about typos in column/field names.

Your first example can be fixed by specifying list of columns you want to select

```
    users := []User{}
    _, err = app.DB.Query(
        &users,
        `select
                users.name, users.email
            from users, parcels
            where
                st_dwithin(users.geom, parcels.geom, 0.005)`,
    )
```

ORM automatically specifies that list so everything should already work. I am not sure how `users` and `parcels` table are joined, but you can specify table manually:

```
var users []User
db.Model(&users).Table("parcels").Where("st_dwithin(users.geom, parcels.geom, 0.005)")
```

If you need join you can consider definite has-one/belongs-to relation to `Parcel` struct.

**Comment by jeromenerf** [comment] 2016-10-18 14:02
@vmihailenco sorry, been busy too :)

Thanks for the `Table()` tip.

However, concerning `override`, you did not answer my question (which may not have been clear enough) : 

- given a `User` model and a UserP model which override `User` and adds an additional `Password` column
- given that both models share the same table in pg
- then UserP requests work just fine 
- but anything like `db.Model(&user).Column("user.*", 'SomeRelation").Select()` will fail with a `pg: can't find column password in model User` error

It seems that pg returning an error when it finds a column it can't map to the model is going to be a limitation. I can't see an easy fix for this problem, is it ongoing in v5?

**Comment by vmihailenco** [comment] 2016-10-20 12:07
Erroring on a missing column is a feature, not a bug :) It is probably inconvenient in some cases, but it is hard to say how much without some experience. But I see some value in being strict in this case, because otherwise any mis-spelled column name means you silently drop some data.

I think following query should work:

```
db.Model(&user).Column("SomeRelation").Select()
```

because it should select only columns from `User` struct and "SomeRelation", because go-pg by default specifies full list of know columns in `SELECT` query. But when you provide at least one column using `Column("user.*")` it uses list that you provided it. We can also consider expanding `User.*` into the list of known column names `user.id, user.name`, but I can't think of good/obvious syntax for this.

**Closed** 2017-01-03 11:21 UTC
