### ISSUE TITLE
How select all columns from table?

### ISSUE THREAD

**Issue by Anochin** [go-pg/pg#1693] opened 2020-08-18 07:45 UTC
I want select all columns from unknown table structure. In result I want have []map[string]interface{}? Where key in map is field name.

**Comment by maxless** [comment] 2020-08-20 15:33
Not yet possible due to #1121 
But here's a neat trick:
```
var str string
_, err := DB.Query(&str, `SELECT json_agg(t) FROM MyTable AS t`)
```

str will be a JSON array string. The caveat is that all keys will be lowercase.

**Comment by vmihailenco** [comment] 2020-08-22 05:39
Closing as duplicate of https://github.com/go-pg/pg/issues/1121

**Closed as completed by vmihailenco** 2020-08-22 05:39 UTC
