### ISSUE TITLE
Support for metrics instrumentation

### ISSUE THREAD

**Issue by nitin302** [go-pg/pg#1522] opened 2020-02-20 05:58 UTC
I'm trying to use newrelic instrumentation to push datastore segment metrics automatically for all queries.

New relic's has direct support for packages using lib/pq (https://godoc.org/github.com/newrelic/go-agent/v3/integrations/nrpq). But go-pg/pg does not seem to use the lib/pq driver directly.

- How else can I achieve this without manual creating a datastore segment around every query call.
- Is there a roadmap to allow to instrument new relic or other such providers in the future.

**Comment by vmihailenco** [comment] 2020-02-22 14:03
Closing as duplicate of https://github.com/go-pg/pg/issues/1470

**Closed by vmihailenco** 2020-02-22 14:03 UTC
