### ISSUE TITLE
ERROR #22021 invalid byte sequence for encoding "UTF8": 0xf9:

### ISSUE THREAD

**Issue by DuckerMan** [go-pg/pg#932] opened 2018-07-28 16:48 UTC
My code is

```

type AttachmentsNew struct {
	Id int
	OwnerId int
	Hashkey string 
	Time int
	FileInfo string
	Filepath string
	Doctype string
}

```

```

attachment := &AttachmentsNew{Id:1, OwnerId: ownerId, Hashkey: "test", Time:1, FileInfo:file.oldname, Filepath:file.path, Doctype:file.documentType};
Database.Insert(attachment);

```

I got error:

`ERROR #22021 invalid byte sequence for encoding "UTF8": 0xf9:`

**Comment by vmihailenco** [comment] 2018-07-30 07:41
Closing since there is no way to reproduce this.

**Closed by vmihailenco** 2018-07-30 07:41 UTC
