### ISSUE TITLE
has-many SELECT error

### ISSUE THREAD

**Issue by gmolveau** [go-pg/pg#501] opened 2017-03-22 20:58 UTC
Hello ! Thank you for your work :)

I've got a problem with a simple has-many SELECT query.
I've got 2 models for my example : 
```
User { 
    ID               int,
    GiftsReceived    []*Gift `pg:",fk:Receiver"`
} 

Gift {
    ID           int,
    SenderID    int,
    ReceiverID  int,
    Sender       *User,
    Receiver     *User,
    Price        int,
    Opened       bool
}
```
A gift matches 2 users.
I'd like to get all the Gifts where receiver_id is 1 and opened is false.
When I try the different methods of the documentation I always get an empty array back.
Like this one : 

```
user := User{ID : 1}
gifts := []*Gift{}
_ := db.Model(&gifts).
		Column("gift.*","Sender").
		Column("gift.*","Receiver").
		Where("receiver_id = ?", user.ID).
                Where("opened <> ?", true).
		Select()

// gifts is returned as []
```

Thank you so much for your help !

**Comment by vmihailenco** [comment] 2017-03-23 11:28
Not sure what is wrong, but you can start with fixing typos
- `Where("receiver_id = ", user.ID)` -> `Where("receiver_id = ?", user.ID)`
- `Where("opened <> ", true)` -> `Where("opened <> ?", true).`
- `Column("gift.*","Receiver").` - "gift.*" is specified twice

Othen than that everything looks good.

**Comment by gmolveau** [comment] 2017-03-23 12:28
Thank you for your answer. I've fixed the typos in my code but the problem remains. There is no error but the array is still empty.

I fixed it by doing this :
```
	var ids[] int
	if _, err := c.DB.Query(&ids, `SELECT t.id from gifts t where opened <> 'true' and receiver_id = ?`, user.ID); err != nil {
		return nil,err
	}
	gifts := []models.Gift{}
	for _,v := range ids {
		t := models.Gift{ID:v}
		if err := c.GetGift(&t); err != nil {
			return nil,err
		}
		fmt.Println(t)
		gifts = append(gifts,t)
	}
	return gifts,nil
```
but it seems like I'm doing too much.

**Comment by madhukar93** [comment] 2017-07-20 16:44
have you tried logging the queries that are generated by pg-go ?
Also are you supposed to instantiate the slice to be populated 
`gifts := []*Gift{}`
I think it's supposed to be just declared 
so the following should do -
`var gifts []Gift`

**Comment by vmihailenco** [comment] 2017-07-24 12:55
Closing since I am not sure what to do here. If you are still interested please reopen with reproducible example that I can run...

**Closed by vmihailenco** 2017-07-24 12:55 UTC
