### ISSUE TITLE
Passing []net.IP in WHERE clause

### ISSUE THREAD

**Issue by roylee17** [go-pg/pg#1701] opened 2020-08-29 22:26 UTC
It works for hardcoded ip list.
```
db.Query(&hosts, `
  SELECT * 
  FROM hosts
  WHERE ip IN ('192.168.1.1', '192.168.1.2')
`
```

It doesn't work when passed as as parameters:

```
ipList := []net.IP{
  net.ParseIP("192.168.1.1"),
  net.ParseIP("192.168.1.2"),
}

db.Query(&hosts, `
  SELECT * 
  FROM hosts
  WHERE ip IN (?)
`, pg.IN(ipList)
```

Tried a few alternatives with no luck so far.
* Pass the list as []string
* Pass the list as single pre-formated string ''192.168.1.1', '192.168.1.2'" 
...

So far the only way I got it work is to pre-format the "whole query" string", but I wonder what's the proper way to do it with go-pg. Or we haven't supported it at the moment?

**Comment by vmihailenco** [comment] 2020-10-01 12:07
"Pass the list as []string" definitely works - there are examples in the code and docs. Closing since reproduction is missing.

**Closed as completed by vmihailenco** 2020-10-01 12:07 UTC
