### ISSUE TITLE
Can't have different pg table names for the same Go struct

### ISSUE THREAD

**Issue by hsluoyz** [go-pg/pg#1874] opened 2021-04-17 11:08 UTC
See details at: https://github.com/casbin/casbin-pg-adapter/issues/26

**Comment by kilosonc** [comment] 2021-04-18 04:08
In [docs](https://pkg.go.dev/github.com/go-pg/pg/v10#example-DB.Model-InsertDynamicTableName) I found dynamic table name, but when I use it in my project, there's always an error ` pgadapter.NewAdapter: ERROR #42601 syntax error at or near "("`
```go
func (a *Adapter) createTableifNotExists() error {
	err := a.db.Model((*CasbinRule)(nil)).Table(a.tableName).CreateTable( &orm.CreateTableOptions{
		Temp:        false,
		IfNotExists: true,
	})
	if err != nil {
		return err
	}
	return nil
}
```

**Comment by hsluoyz** [comment] 2021-04-18 08:15
@closetool can you provide a full example code, maybe a github repo?

**Comment by kilosonc** [comment] 2021-04-18 10:46
@hsluoyz https://github.com/closetool/casbin-pg-adapter-1/tree/tablename

**Comment by arafat-java** [comment] 2021-04-21 04:10
Guys, Any tentative timelines for fixing this

**Comment by hsluoyz** [comment] 2021-04-21 05:05
@vmihailenco

**Comment by arafat-java** [comment] 2021-04-23 00:53
Guys, any update ?

**Comment by vmihailenco** [comment] 2021-07-20 09:15
Closing as duplicate of https://github.com/go-pg/pg/issues/1810

**Closed as completed by vmihailenco** 2021-07-20 09:15 UTC
