### ISSUE TITLE
 insert composite type array

### ISSUE THREAD

**Issue by wangyiran125** [go-pg/pg#1481] opened 2019-12-16 09:30 UTC
sql
```
CREATE TABLE public.tiantang_page (
	href varchar NOT NULL,
	status int4 NOT NULL,
	description varchar NOT NULL,
	urls url[] NULL
);

CREATE TYPE url AS (
	url varchar,
	status int4);
```

 insert composite type array
```
type url  struct {
	url string
	status int 
}
	var urls [1]url
	urls[0] = url{
		url:    "",
		status: 0,
	}
	update := "UPDATE \"public\".\"tiantang_page\" SET \"urls\"=$1 where \"href\"=$2;"
	r, err := db.Exec(update, pq.Array(urls),href)
	if err != nil {
		log.Fatal(err)
	}
```
error

> sql: converting argument $1 type: unsupported type parsetest.url, a struct

**Comment by vmihailenco** [comment] 2019-12-16 10:17
Duplicate of https://github.com/go-pg/pg/issues/1197

**Closed by vmihailenco** 2019-12-16 10:17 UTC
